# Generated by Django 6.0.4 on 2026-04-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundemail',
            name='html_body',
            field=models.TextField(blank=True),
        ),
    ]
